In [51]:
import pandas as pd
import numpy as np

In [52]:
df=pd.read_csv("mail_data.csv")

In [53]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [54]:
df.shape

(5572, 2)

In [55]:
df.value_counts("Category")

Category
ham     4825
spam     747
Name: count, dtype: int64

In [56]:
df.loc[df['Category']=='spam','Category',]=0

In [57]:
df.loc[df['Category']=='ham','Category',]=1

In [58]:
df.head()

  Category                                            Message
0        1  Go until jurong point, crazy.. Available only ...
1        1                      Ok lar... Joking wif u oni...
2        0  Free entry in 2 a wkly comp to win FA Cup fina...
3        1  U dun say so early hor... U c already then say...
4        1  Nah I don't think he goes to usf, he lives aro...

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
X_train,X_test,Y_train,Y_test=train_test_split(df.Message,df.Category,test_size=0.2)

In [61]:
X_train.shape

(4457,)

In [62]:
X_test.shape

(1115,)

In [63]:
from sklearn.feature_extraction.text import CountVectorizer

In [64]:
v=CountVectorizer()

In [65]:
X_train_cv=v.fit_transform(X_train.values)

In [66]:
X_train_cv

<4457x7680 sparse matrix of type '<class 'numpy.int64'>'
	with 59204 stored elements in Compressed Sparse Row format>

In [67]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [68]:
X_train_cv.shape

(4457, 7680)

In [69]:
v.get_feature_names_out().shape

(7680,)

In [70]:
from sklearn.naive_bayes import MultinomialNB

In [71]:
from sklearn.pipeline import Pipeline
clf=Pipeline([('vectorizer',CountVectorizer()),
             ('nb',MultinomialNB())])

In [72]:
Y_train.shape

(4457,)

In [73]:
# If labels are numeric (0/1 or class IDs)
Y_train = Y_train.astype(int)

# If labels are strings (like "spam"/"ham")
Y_train = Y_train.astype(str)

In [74]:
clf.fit(X_train,Y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [75]:
y_pred=clf.predict(X_test)

In [76]:
Y_test = Y_test.astype(str)
y_pred = y_pred.astype(str)

In [77]:
from sklearn.metrics import classification_report

In [78]:
classification_report(Y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.97      0.92      0.94       149\n           1       0.99      1.00      0.99       966\n\n    accuracy                           0.99      1115\n   macro avg       0.98      0.96      0.97      1115\nweighted avg       0.99      0.99      0.99      1115\n'

In [79]:
from sklearn.metrics import accuracy_score

In [81]:
pred_on_train_data=clf.predict(X_train)

In [82]:
acc_train=accuracy_score(Y_train,pred_on_train_data)

In [83]:
print(acc_train)

0.9937177473636976

In [84]:
pred_on_test_data=clf.predict(X_test)

In [86]:
acc_test=accuracy_score(Y_test,pred_on_test_data)

In [87]:
print(acc_test)

0.9856502242152466